Models/ViewModels/ReporteFotoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IntegramsaUltimate.Models.ViewModels
{
    public class ReporteFotoViewModel
    {
        public string proposito { get; set; }
        public int? idFotoNueva { get; set; }
        public int? idFotoVieja { get; set; }

        public byte[] fotoNueva { get; set; }

        public byte[] fotoVieja { get; set; }

        public string observaciones { get; set; }
        public string codigoReporte { get; set; }

        public string plaza { get; set; }
        public string cadena { get; set; }
        public string nombreTienda { get; set; }
        public string determinante { get; set; }

        public string promotor { get; set; }
    }

}

Controllers/ReporteFotoController.cs
using IntegramsaUltimate.Models.FilterViewModel;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using IntegramsaUltimate.Models.TableViewModels;
using IntegramsaUltimate.Models.ViewModels;
using IntegramsaUltimate.Models;

namespace IntegramsaUltimate.Controllers
{
    public class ReporteFotoController : BaseController
    {
        public class FotoVieja
        {
            public int id { get; set; }
            public byte[] foto { get; set; }
        }

        // GET: FotoAnaquel
        public ActionResult Index()
        {
            ObtieneSesion();
            //si el usuario es un cliente
            if (oUsuario.idTipoUsuario == 6)
                ViewBag.idCliente = oUsuario.usuarioCliente.First().idCliente;

            return View();
        }

        public ActionResult Ver(int id, int idProposito)
        {
            reporteTienda oReporteTienda= db.reporteTienda.Find(id);
            
            ReporteFotoViewModel model = new ReporteFotoViewModel();

            FotoVieja oFotoVieja = obtenerUltimaFoto(idProposito, oReporteTienda.rutaIntinerario.tienda.id, oReporteTienda.idUsuarioPromotor, oReporteTienda.fechaEntrada);


            model.codigoReporte = oReporteTienda.rutaIntinerario.ruta.codigoRuta;
            model.fotoNueva = oReporteTienda.reporteTiendaFoto.Where(d=>d.idFotoProposito==idProposito).FirstOrDefault().foto;
            model.idFotoNueva = oReporteTienda.reporteTiendaFoto.Where(d => d.idFotoProposito == idProposito).FirstOrDefault().id;
            if (model.fotoVieja != null) //si existe la foto vieja
            {
                model.fotoVieja = oFotoVieja.foto;
                model.idFotoVieja = oFotoVieja.id;
            }
            model.observaciones = oReporteTienda.observaciones;
            model.proposito = oReporteTienda.reporteTiendaFoto.FirstOrDefault().cFotoProposito.nombre;
            model.nombreTienda = oReporteTienda.rutaIntinerario.tienda.nombre;
            model.determinante = oReporteTienda.rutaIntinerario.tienda.codigo;
            model.promotor=oReporteTienda.usuario.nombre+" "+oReporteTienda.usuario.paterno+" "+oReporteTienda.usuario.materno;
            model.plaza = oReporteTienda.rutaIntinerario.tienda.cmunicipio.PlazaMunicipio.FirstOrDefault().cPlaza.nombre;
            model.cadena = oReporteTienda.rutaIntinerario.tienda.cadena.nombre;
            model.observaciones = oReporteTienda.observaciones;

            return View(model);
        }

        public ActionResult Foto(int idFoto)
        {
            reporteTiendaFoto oRF = db.reporteTiendaFoto.Find(idFoto);

            return base.File(oRF.foto, "image/jpeg");

        }

        public ActionResult VerFirma(int id)
        {
            reporteTienda oRF = db.reporteTienda.Find(id);

            return base.File(oRF.foto, "image/jpeg");

        }
        #region Grid
        public ActionResult Listado(FilterFotoAnaquelViewModel model)
        {

            return View(model);
        }

        public ActionResult JsonGrid([DataSourceRequest] DataSourceRequest request, FilterFotoAnaquelViewModel model)
        {
            IEnumerable<TableFotoAlmacenViewModel> lst = null;
            
            //casteamos fechas
            DateTime FechaInicio = DateTime.ParseExact(model.fechaInicio + " 00:00:00", "dd/MM/yyyy HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
            DateTime FechaFin = DateTime.ParseExact(model.fechaFin + " 23:59:59", "dd/MM/yyyy HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);

           
            lst = from d in db.reporteTienda.ToList()
                    where d.idEstado==1 && d.idUsuarioPromotor==model.cboPromotores && d.fechaEntrada>= FechaInicio && d.fechaEntrada<=FechaFin
                    select new TableFotoAlmacenViewModel
                    {
                        id = d.id,
                        fecha=d.fechaEntrada,
                        observaciones=d.observaciones,
                        existeFirma = (new Func<string>(() =>
                        {
                            try
                            {
                                if (d.foto!=null)
                                {
                                    return "Si";
                                }
                                else
                                {
                                    return "No";
                                }

                            }
                            catch { return "No"; }
                        }
                                                   )
                                  )(),
                        existeFotoUnica=  (new Func<string>(() => {
                                                            try { 
                                                                    if(d.reporteTiendaFoto.Where(c=>c.idFotoProposito==1).Count()>0){
                                                                         return "Si";
                                                                    }
                                                                    else
                                                                    {
                                                                        return "No";
                                                                    }
                                                                    
                                                                } 
                                                            catch { return "No"; } 
                                                        }
                                                  )
                                 )(),
                        existeFotoConcurso = (new Func<string>(() =>
                        {
                            try
                            {
                                if (d.reporteTiendaFoto.Where(c => c.idFotoProposito == 2).Count() > 0)
                                {
                                    return "Si";
                                }
                                else
                                {
                                    return "No";
                                }

                            }
                            catch { return "No"; }
                        }
                                        )
                       )(),
                        existeFotoAntesDespues = (new Func<string>(() =>
                        {
                            try
                            {
                                if (d.reporteTiendaFoto.Where(c => c.idFotoProposito == 3).Count() > 0)
                                {
                                    return "Si";
                                }
                                else
                                {
                                    return "No";
                                }

                            }
                            catch { return "No"; }
                        }
                                                  )
                                 )(),
                        nombreTienda=d.rutaIntinerario.tienda.nombre,
                        encargado=d.encargado,
                        codigoRuta=d.rutaIntinerario.ruta.codigoRuta
                       

                    };


            return Json(lst.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region HELPER

        /// <summary>
        /// metodo que obtiene la ultima foto respecto a otra foto otorgada
        /// </summary>
        /// <param name="idTipoProposito"></param>
        /// <param name="idTienda"></param>
        /// <param name="idPromotor"></param>
        /// <param name="fecha"></param>
        /// <returns></returns>
        private FotoVieja obtenerUltimaFoto(int? idTipoProposito, int? idTienda, int? idPromotor, DateTime? fecha)
        {

            FotoVieja oFotoVieja= null;
            try
            {
                var oReporteFoto = (from d in db.reporteTiendaFoto
                                   where d.reporteTienda.idEstado == 1 && d.reporteTienda.rutaIntinerario.idTienda == idTienda
                                   && d.idFotoProposito == idTipoProposito && d.reporteTienda.idUsuarioPromotor == idPromotor
                                   && d.reporteTienda.fechaEntrada<fecha
                                   orderby d.reporteTienda.fecha descending
                                   select d).FirstOrDefault();

                if (oReporteFoto != null) //si no es null
                {
                    oFotoVieja.foto = oReporteFoto.foto;
                    oFotoVieja.id = oReporteFoto.id;
                   
                }
            }
            catch { oFotoVieja= null; }

            return oFotoVieja;
        }
        #endregion
    }
}

Views/ReporteFoto/Index.cshtml
@{
    ViewBag.Title = "Foto Anaquel";

    int? idCliente = (int?)ViewBag.idCliente;
   
}
<div style="background-color:#eee;padding:10px" class="head-module">
    <form id="frmBuscador">
        <span style="margin-right:35px" class="modulo-titulo">@ViewBag.Title</span>
        <br />
        <i>Selecciona los valores de tu búsqueda</i>
        <br />
        @if(idCliente==null){
            @Html.Partial("~/Views/Partials/Filtros/_ClientePromotor.cshtml")
        }
        else
        {
            @Html.Partial("~/Views/Partials/Filtros/_Promotores.cshtml",idCliente)
        }
        <span>
            <label>Fecha Inicio</label>
            @Html.Kendo().DatePicker().Name("fechaInicio").Min("01/01/2016").Max(DateTime.Now).Value(DateTime.Now).Format("dd/MM/yyyy")
        </span>
        <span>
            <label>Fecha Fin</label>
            @Html.Kendo().DatePicker().Name("fechaFin").Min("01/01/2016").Max(DateTime.Now).Value(DateTime.Now).Format("dd/MM/yyyy")
        </span>
        <br />
        <div style="text-align:right;padding-top:5px;">
            <span>
                <input class="btn-success" type="submit" value="Buscar" />
            </span>
        </div>
    </form>

</div>
<br />
<div id="divGrid">

</div>

<script>
    $(document).ready(function () {

        //busca
        $("#frmBuscador").submit(function (e) {
            e.preventDefault();
            url = "@Url.Content("~/ReporteFoto/Listado")"+"?"+$(this).serialize();
            alert(url);

            $("#divGrid").load(url);

        })

    });

    //funciones
    function jsAbreFoto(id,idProposito) {
        url="@Url.Content("~/ReporteFoto/Ver")"+"?id="+id+"&idProposito="+idProposito
        jsShowDialog(url, 800,550, "Foto")



    }

    function jsVerFoto(id) {
        url = "@Url.Content("~/ReporteFoto/VerFirma")" + "?id=" + id
        window.open(url);
       

    }
</script>

Views/ReporteFoto/Listado.cshtml
@using IntegramsaUltimate.Models.FilterViewModel
@model FilterFotoAnaquelViewModel
@{
    Layout = null;
}

<div class="row">

    <div class="col-md-12">
        @(Html.Kendo().Grid<IntegramsaUltimate.Models.TableViewModels.TableFotoAlmacenViewModel>()
                    .Name("tabla")

                     .Columns(c =>
                        {
                            c.Bound(p => p.id).Title("#").Hidden();
                            c.Bound(p => p.codigoRuta).Title("Código");

                            c.Bound(p => p.fecha).Format("{0:dd/MM/yyyy}").Title("Fecha");
                            c.Bound(p => p.nombreTienda).Title("Nombre Tienda");
                            c.Bound(p => p.encargado).Title("Encargado").Hidden();
                            c.Bound(p => p.observaciones).Title("Observaciones");

                            c.Bound(p => p.id).Title("Firma").ClientTemplate(@"# if(existeFirma!=null &&existeFirma!='No'){ # <input type='button' value='Ver Foto' onclick='jsVerFoto(#=id#)'   /> #} #").Width(30);                          
                            c.Bound(p => p.id).Title("Unica").ClientTemplate(@"# if(existeFotoUnica!=null &&existeFotoUnica!='No'){ # <input type='button' value='Ver Foto' onclick='jsAbreFoto(#=id#,1)'   /> #} #").Width(30);
                            c.Bound(p => p.id).Title("Concurso").ClientTemplate(@"# if(existeFotoConcurso!=null && existeFotoConcurso!='No'){ # <input type='button' value='Ver Foto' onclick='jsAbreFoto(#=id#,2)'   /> #} #").Width(30);
                            c.Bound(p => p.id).Title("Antes-Despues").ClientTemplate(@"# if(existeFotoAntesDespues!=null && existeFotoAntesDespues!='No'){ # <input type='button' value='Ver Foto' onclick='jsAbreFoto(#=id#,3)'   /> #} #").Width(30);
                        
                        })
                        .ToolBar(tools => tools.Excel())
                        .Pageable()
                        .Sortable()
                        .Filterable()
                        .Groupable()
                        .Excel(excel => excel
                            .FileName("reporte.xlsx")
                            .AllPages(true)
                                     .ProxyURL(Url.Action("JsonGrid", "ReporteFoto", new { cboPromotores = Model.cboPromotores, fechaInicio = Model.fechaInicio, fechaFin = Model.fechaFin }))
                         )
                        .Resizable(resize => resize.Columns(true))
                        .DataSource(d => d.Ajax()
                                    .Sort(sort =>
                                    {
                                        sort.Add("Fecha").Descending();
                                    })
                                                   .Read(r => r.Action("JsonGrid", "ReporteFoto", new { cboPromotores = Model.cboPromotores, fechaInicio = Model.fechaInicio, fechaFin = Model.fechaFin }))
                        )

        )
    </div>
</div>

Views/ReporteFoto/Ver.cshtml
@model IntegramsaUltimate.Models.ViewModels.ReporteFotoViewModel
@{
    Layout = null;

    //foto
    string base64String1 = null,base64String2=null;
    
    WebImage wi = null;
    if (Model.fotoVieja !=null)
    {
        wi = new WebImage((byte[])Model.fotoVieja);
        base64String1 = "data:image/jpg;base64," + Convert.ToBase64String(wi.GetBytes());
    }

    if (Model.fotoNueva != null)
    {
        wi = new WebImage((byte[])Model.fotoNueva);
        base64String2 = "data:image/jpg;base64," + Convert.ToBase64String(wi.GetBytes());
    }
}


<div>
    <h2>@Model.cadena, @Model.nombreTienda, @Model.determinante, @Model.plaza</h2>
    <h3>@Model.promotor</h3>
    <h4>@Model.proposito</h4>
</div>

<div style="border-top:#999;" >
    <div class="mitad float" style="text-align:center;">
        <img onclick="window.open('@Url.Content("~/ReporteFoto/Foto/?idFoto="+Model.idFotoVieja) '); " src="@base64String1" style="max-width:80%; max-height:250px; border:1px solid #888; cursor:pointer" />
    </div>
    <div class="mitad float" style="text-align:center;">
        <img onclick="window.open('@Url.Content("~/ReporteFoto/Foto/?idFoto="+Model.idFotoNueva) ');" src="@base64String2" style="max-width:80%; max-height:250px;  border:1px solid #888; cursor:pointer;" />
    </div>
</div>

<div>
    <p><b>Observaciones: </b>@Model.observaciones</p>
</div>