Controllers/ReporteAsistenciaNewController.cs
using IntegramsaUltimate.Models.FilterViewModel;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using IntegramsaUltimate.Models.TableViewModels;
using IntegramsaUltimate.Models.ViewModels;

namespace IntegramsaUltimate.Controllers
{
    public class ReporteAsistenciaNewController : BaseController
    {
        // GET: ReporteAsistenciaNew
        public ActionResult Index()
        {
            ObtieneSesion();
            //si el usuario es un cliente
            if (oUsuario.idTipoUsuario == 6)
                ViewBag.idCliente = oUsuario.usuarioCliente.First().idCliente;


            ViewBag.lstClientes = Models.HelperModels.Cliente.getClientesSL();

            return View();
        }


        public ActionResult VerMapa(int idReporteTienda)
        {

            ReporteAsistenciaNewMapa oRANM = (from d in db.reporteTienda
                                              where d.id == idReporteTienda && d.idEstado == 1
                                              select new ReporteAsistenciaNewMapa
                                              {
                                                  tiendaLatitud = d.rutaIntinerario.tienda.ubicacion.Latitude.ToString(),
                                                  tiendaLongitud = d.rutaIntinerario.tienda.ubicacion.Longitude.ToString(),
                                                  posicionLatitud = d.ubicacion.Latitude.ToString(),
                                                  posicionLongitud = d.ubicacion.Longitude.ToString(),
                                                  Tienda = d.rutaIntinerario.tienda.nombre
                                              }).First();

            return View(oRANM);
        }

        #region Grid
        public ActionResult Listado(ReporteAsistenciaNewFilterViewModel model)
        {


            return View(model);
        }

        public ActionResult JsonGrid([DataSourceRequest] DataSourceRequest request, ReporteAsistenciaNewFilterViewModel model)
        {
            IEnumerable<TableReporteAsistenciaNewViewModel> lst = null;
            IQueryable<TableReporteAsistenciaNewViewModel> query = null;
            List<TableReporteAsistenciaNewViewModel> reporte = new List<TableReporteAsistenciaNewViewModel>();
            DateTime FechaInicio;
            DateTime FechaFin;
           // DateTime DateLess3Months = DateTime.Today.AddMonths(-3);
           // string DateLess3MonthsString = DateLess3Months.ToString("dd/MM/yyyy");
           // DateTime.ParseExact("04/30/2013 23:00", "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture);

            if (model.fechaInicio == null)
            {
                FechaInicio = DateTime.ParseExact(DateTime.Today.AddDays(-3).ToString("dd/MM/yyyy") + " 00:00:00", "dd/MM/yyyy HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
            }
            else
            {
                FechaInicio = DateTime.ParseExact(model.fechaInicio + " 00:00:00", "dd/MM/yyyy HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
            }
            if (model.fechaFin == null)
            {
                DateTime dateTimeNow = DateTime.Now;
                string dateOnlyString = dateTimeNow.ToString("dd/MM/yyyy");
                FechaFin = DateTime.ParseExact(dateOnlyString + " 23:59:59", "dd/MM/yyyy HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
            }
            else
            {
                FechaFin = DateTime.ParseExact(model.fechaFin + " 23:59:59", "dd/MM/yyyy HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
            }

            //Verificamos si la fecha de inicio es mayor a 3 meses para que busque en otra tabla 
            if (model.idCliente != null) {
                if (FechaInicio >= DateTime.Today.AddMonths(-3))
                {

                    var querys = (from d in db.fnReporteAsistenciaNew(FechaInicio, FechaFin).Where(d=>d.idCliente == model.idCliente)
                                  group d by
                                  new TableReporteAsistenciaNewViewModel
                                  {
                                      id = d.id,
                                      idCliente = d.idCliente,
                                      Plaza = d.Plaza,
                                      Promotor = d.nombre,
                                      Cadena = d.cadena,
                                      Tienda = d.tienda,
                                      Determinante = d.codigo,
                                      Fecha = d.dfechaSalida,
                                      HoraEntrada = d.horaEntrada,
                                      HoraSalida = d.horaSalida,
                                      Perimetro = d.perimetro,
                                      tiempoTienda = d.tiempoTienda,
                                      ano = d.ano,
                                      numSemana = d.numSemana

                                  } into grupo
                                  select grupo).ToList();
                    foreach (var grupo in querys)
                    {
                        reporte.Add(new TableReporteAsistenciaNewViewModel
                        {
                            id = grupo.Key.id,
                            idCliente = grupo.Key.idCliente,
                            Plaza = grupo.Key.Plaza,
                            Promotor = grupo.Key.Promotor,
                            Cadena = grupo.Key.Cadena,
                            Tienda = grupo.Key.Tienda,
                            Determinante = grupo.Key.Determinante,
                            Fecha = grupo.Key.Fecha,
                            HoraEntrada = grupo.Key.HoraEntrada,
                            HoraSalida = grupo.Key.HoraSalida,
                            Perimetro = grupo.Key.Perimetro,
                            tiempoTienda = grupo.Key.tiempoTienda,
                            ano = grupo.Key.ano,
                            numSemana = grupo.Key.numSemana
                        });
                    }

                }
                else
                {
                    var querys = (from d in db.fnReporteAsistenciaPas(FechaInicio, FechaFin).Where(d => d.idCliente == model.idCliente)
                                  group d by
                                  new TableReporteAsistenciaNewViewModel
                                  {
                                      id = d.id,
                                      idCliente = d.idCliente,
                                      Plaza = d.Plaza,
                                      Promotor = d.nombre,
                                      Cadena = d.cadena,
                                      Tienda = d.tienda,
                                      Determinante = d.codigo,
                                      Fecha = d.dfechaSalida,
                                      HoraEntrada = d.horaEntrada,
                                      HoraSalida = d.horaSalida,
                                      Perimetro = d.perimetro,
                                      tiempoTienda = d.tiempoTienda,
                                      ano = d.ano,
                                      numSemana = d.numSemana

                                  } into grupo
                                  select grupo).ToList();
                    foreach (var grupo in querys)
                    {
                        reporte.Add(new TableReporteAsistenciaNewViewModel
                        {
                            id = grupo.Key.id,
                            idCliente = grupo.Key.idCliente,
                            Plaza = grupo.Key.Plaza,
                            Promotor = grupo.Key.Promotor,
                            Cadena = grupo.Key.Cadena,
                            Tienda = grupo.Key.Tienda,
                            Determinante = grupo.Key.Determinante,
                            Fecha = grupo.Key.Fecha,
                            HoraEntrada = grupo.Key.HoraEntrada,
                            HoraSalida = grupo.Key.HoraSalida,
                            Perimetro = grupo.Key.Perimetro,
                            tiempoTienda = grupo.Key.tiempoTienda,
                            ano = grupo.Key.ano,
                            numSemana = grupo.Key.numSemana
                        });
                    }
                }
            }
            else {
                if (FechaInicio >= DateTime.Today.AddMonths(-3))
                {

                    var querys = (from d in db.fnReporteAsistenciaNew(FechaInicio, FechaFin)
                                  group d by
                                  new TableReporteAsistenciaNewViewModel
                                  {
                                      id = d.id,
                                      idCliente = d.idCliente,
                                      Plaza = d.Plaza,
                                      Promotor = d.nombre,
                                      Cadena = d.cadena,
                                      Tienda = d.tienda,
                                      Determinante = d.codigo,
                                      Fecha = d.dfechaSalida,
                                      HoraEntrada = d.horaEntrada,
                                      HoraSalida = d.horaSalida,
                                      Perimetro = d.perimetro,
                                      tiempoTienda = d.tiempoTienda,
                                      ano = d.ano,
                                      numSemana = d.numSemana

                                  } into grupo
                                  select grupo).ToList();
                    foreach (var grupo in querys)
                    {

Views/ReporteAsistenciaNew/Index.cshtml
@{
    ViewBag.Title = "Asistencia";
    int? idCliente = (int?)ViewBag.idCliente;
}


<div style="background-color:#eee;padding:10px" class="head-module">
    <form id="frmBuscar">
        <span style="margin-right:35px" class="modulo-titulo">@ViewBag.Title</span>
        
        <br />
        @if (idCliente == null)
        {
            @Html.Partial("~/Views/Partials/Filtros/_Clientes.cshtml")
        }
        else //si entra el cliente
        {
            @Html.Hidden("cboCliente",idCliente)
        }


        <span>
            <label>Fecha Inicio</label>
            @Html.Kendo().DatePicker().Name("fechaInicio").Min("01/01/2016").Max(DateTime.Now).Value(DateTime.Now).Format("dd/MM/yyyy")
        </span>
        <span>
            <label>Fecha Fin</label>
            @Html.Kendo().DatePicker().Name("fechaFin").Min("01/01/2016").Max(DateTime.Now).Value(DateTime.Now).Format("dd/MM/yyyy")
        </span>
        <span>
            <input class="btn btn-success" type="submit" value="Buscar" />
        </span>
    </form>
</div>
<hr />
<div id="divGrid">

</div>

<script>

    $(document).ready(function () {

        //eliminamos y ponemos el body en fluid
        $(".body-content").removeClass("container");
        $(".body-content").addClass("container-fluid");

        $("#cboCliente").change(function () {

            idCliente = $("#cboCliente").prop("value");
            fechaInicio=$("#fechaInicio").prop("value")
            fechaFin = $("#fechaFin").prop("value");
           
            url = "@Url.Content("~/ReporteAsistenciaNew/Listado")" + "?idCliente=" + idCliente + "&fechaInicio=" + fechaInicio + "&fechaFin=" + fechaFin;

            $("#divGrid").load(url);

        })

        $("#cboCliente").change(); //invocamos el listado

        $("#frmBuscar").submit(function (e) {
            e.preventDefault();

            url = "@Url.Content("~/ReporteAsistenciaNew/Listado")" + "?idCliente=" + idCliente
            parametros = $(this).serialize();
           
            $.post(url, parametros, function (data) {

                $("#divGrid").html(data);

            })
        })


    })

    //funciones
    function jsAbreMapa(idReporteTienda) {
        url="@Url.Content("~/ReporteAsistenciaNew/VerMapa")"+"?idReporteTienda="+idReporteTienda
        jsShowDialog(url, 700,500, "Ruta")



    }
</script>

Views/ReporteAsistenciaNew/Listado.cshtml
@using IntegramsaUltimate.Models.FilterViewModel
@model ReporteAsistenciaNewFilterViewModel
@{
    Layout = null;
}

<div class="row">

    <div class="col-md-12">
        @(Html.Kendo().Grid<IntegramsaUltimate.Models.TableViewModels.TableReporteAsistenciaNewViewModel>()
                    .Name("tabla")

                     .Columns(c =>
                     {
                         c.Bound(p => p.id).Title("#").Hidden();
                         c.Bound(p => p.Plaza).Title("Plaza");
                         c.Bound(p => p.Promotor).Title("Promotor");
                         c.Bound(p => p.Cadena).Title("Cadena");
                         c.Bound(p => p.Tienda).Title("Tienda");
                         c.Bound(p => p.Determinante).Title("Det");
                         c.Bound(p => p.Fecha).Format("{0:dd/MM/yyyy}").Title("Fecha");
                         c.Bound(p => p.HoraEntrada).Title("Entrada");
                         c.Bound(p => p.HoraSalida).Title("Salida");
                         c.Bound(p => p.Perimetro).Title("Perimetro");
                         c.Bound(p => p.tiempoTienda).Title("Tiempo");

                         c.Bound(p => p.id).ClientTemplate(@"# if(id!=null && id!=''){ # <input type='button' value='Ubicación' onclick='jsAbreMapa(#=id#)'   /> #} #").Title("").Width(60);
                     })
                        .ToolBar(tools => tools.Excel())
                        .Pageable()
                        .Sortable()
                        .Filterable()
                        .Groupable()

                        .Excel(excel => excel
                            .FileName("reporte.xlsx")
                            .AllPages(true)
                                     .ProxyURL(Url.Action("JsonGrid", "ReporteAsistenciaNew", new { idCliente = Model.idCliente,fechaInicio=Model.fechaInicio, fechaFin=Model.fechaFin }))
                         )
                        .Resizable(resize => resize.Columns(true))
                        .DataSource(d => d.Ajax()
                                    .Sort(sort =>
                                    {
                                        sort.Add("ano").Ascending();
                                        sort.Add("numSemana").Ascending();
                                        sort.Add("Promotor").Ascending();
                                        sort.Add("Fecha").Descending();
                                        sort.Add("HoraEntrada").Ascending();
                                    })
                                  .Read(r => r.Action("JsonGrid", "ReporteAsistenciaNew", new { idCliente = Model.idCliente, fechaInicio = Model.fechaInicio, fechaFin = Model.fechaFin }))
                        )

        )
    </div>
</div>

Views/ReporteAsistenciaNew/VerMapa.cshtml
@using IntegramsaUltimate.Models
@model IntegramsaUltimate.Models.ViewModels.ReporteAsistenciaNewMapa
@{
    Layout = null;


}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDYH054cm6UIwY8Gl4gwDWNM5K5caPaU9g&amp;sensor=true"></script>
@{string google; }
<div style="height:440px;" id="mapa">
</div>

<script>
    $(document).ready(function () {

        jsLoadMapa();

    });

    function jsLoadMapa() {
        mapOptions = {
            zoom: 15,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        //Creamos el mapa
        map = new google.maps.Map(document.getElementById("mapa"), mapOptions);


        marker = new google.maps.Marker({
            position: new google.maps.LatLng('@Model.tiendaLatitud', '@Model.tiendaLongitud'),
            map: map,
            icon:"@Url.Content("~/Images/markerAzul.png")",
            title: "@Model.Tienda"

        });


        marker2 = new google.maps.Marker({
            position: new google.maps.LatLng('@Model.posicionLatitud', '@Model.posicionLongitud'),
                        map: map,
                        icon:"@Url.Content("~/Images/markerRojo.png")",
                        title: "Ubicación de guardado"

                    });

                    //acomodamos el mapa
                    var bounds = new google.maps.LatLngBounds();
                    bounds.extend(marker.getPosition());
                    bounds.extend(marker2.getPosition());

                    map.fitBounds(bounds);
                    map.setZoom(11);
                }



</script>