Models/HelperModels/Cadena.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntegramsaUltimate.Models.HelperModels
{
    public class Cadena 
    {
        public static bool Existe(string nombre, int id = 0)
        {
            try
            {
                using (IntegramsaUltimateEntities db = new IntegramsaUltimateEntities())
                {

                    IEnumerable<cadena> lst;
                    if (id != 0)
                    {

                        lst = from d in db.cadena
                              where d.idEstado == 1 && d.nombre.Equals(nombre) && d.id != id
                              select d;
                    }
                    else
                    {
                        lst = from d in db.cadena
                              where d.idEstado == 1 && d.nombre.Equals(nombre)
                              select d;
                    }

                    //si existe un usuario regresa true
                    if (lst.Count() > 0)
                        return true;


                }
                return false;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        public static SelectList getCadenasSL(int id=0)
        {
            try
            {
                IntegramsaUltimateEntities db = new IntegramsaUltimateEntities();
                var lst = from d in db.cadena
                          where d.idEstado==1
                          orderby d.nombre
                          select d;


                SelectList slc = null;
                if(id==0)
                    slc=new SelectList(lst, "id", "nombre");
                else
                    slc = new SelectList(lst, "id", "nombre",id);

                return slc;
            }
            catch { return null; }
        }

        public static bool ExistePrefijo(string prefijo, int id = 0)
        {
            try
            {
                using (IntegramsaUltimateEntities db = new IntegramsaUltimateEntities())
                {

                    IEnumerable<cadena> lst;
                    if (id != 0)
                    {

                        lst = from d in db.cadena
                              where d.idEstado == 1 && d.cadenaSugerida.Equals(prefijo) && d.id != id
                              select d;
                    }
                    else
                    {
                        lst = from d in db.cadena
                              where d.idEstado == 1 && d.cadenaSugerida.Equals(prefijo)
                              select d;
                    }

                    //si existe un usuario regresa true
                    if (lst.Count() > 0)
                        return true;


                }
                return false;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}

Models/ViewModels/CadenaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IntegramsaUltimate.Models.ViewModels
{
    public class CadenaViewModel
    {
        public int id { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "El campo nombre no admite mas de 50 caracteres")]
        [Display(Name = "*Nombre")]
        public string nombre { get; set; }

        [Required]
        [Display(Name = "*Giro")]
        public int? idGiro { get; set; }

       
        [StringLength(50, ErrorMessage = "La cadena no admite mas de 50 caracteres")]
        [Display(Name = "Prefijo para determinante")]
        public string cadena { get; set; }
    }
}

Models/cadena.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cadena()
        {
            this.formatoTienda = new HashSet<formatoTienda>();
            this.tienda = new HashSet<tienda>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idGiroComercial { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> sugerida { get; set; }
        public string cadenaSugerida { get; set; }
    
        public virtual cEstado cEstado { get; set; }
        public virtual cGiroComercial cGiroComercial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formatoTienda> formatoTienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tienda> tienda { get; set; }
    }
}

Controllers/CadenaController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IntegramsaUltimate.Models;
using IntegramsaUltimate.Models.TableViewModels;
using Kendo.Mvc.Extensions;
using IntegramsaUltimate.Models.ViewModels;
using System.Data.Entity;

namespace IntegramsaUltimate.Controllers
{
    public class CadenaController : BaseController
    {
        private int idEstado;

        // GET: Cadena
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Nuevo()
        {

            CadenaViewModel model = new CadenaViewModel();

            ObtenerComponentes();


            return View(model);
        }

        [HttpPost]
        public ActionResult Guardar(CadenaViewModel model)
        {
            try
            {
                //model es valido
                if (!ModelState.IsValid)
                {
                    return Content(getErroresModelo());
                }

                //validación de negocio
                if (!Validaciones(model))
                {
                    return Content(error);
                }


                
                //guardamos
                cadena oCadena = new cadena();
                oCadena.idEstado = 1;
                oCadena.fecha = DateTime.Now;
                oCadena.nombre = model.nombre;
                oCadena.cadenaSugerida = model.cadena;
                oCadena.idGiroComercial = model.idGiro;

                db.cadena.Add(oCadena);
                db.SaveChanges();

                return Content("1");

            }
            catch (Exception ex)
            {
                return Content("Ocurrio un error: " + ex.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            ObtenerComponentes();

            //obtenemos la cadena
            cadena oCadena = db.cadena.Find(id);

            CadenaViewModel model = new CadenaViewModel();
            model.nombre = oCadena.nombre;
            model.idGiro = oCadena.idGiroComercial;
            model.cadena = oCadena.cadenaSugerida;
            model.id = oCadena.id;


            return View(model);
        }

        [HttpPost]
        public ActionResult GuardarEditar(CadenaViewModel model)
        {
            try
            {
                //model es valido
                if (!ModelState.IsValid)
                {
                    return Content(getErroresModelo());
                }

                //validación de negocio
                if (!ValidacionesEditar(model))
                {
                    return Content(error);
                }


                //guardamos
                cadena oCadena = db.cadena.Find(model.id);
                oCadena.nombre = model.nombre;
                oCadena.cadenaSugerida = model.cadena;
                oCadena.idGiroComercial = model.idGiro;

                db.Entry(oCadena).State = EntityState.Modified;
                db.SaveChanges();

                return Content("1");

            }
            catch (Exception ex)
            {
                return Content("Ocurrio un error: " + ex.Message);
            }
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                cadena oCadena = db.cadena.Find(id);

                oCadena.idEstado = 3;
                db.Entry(oCadena).State = EntityState.Modified;

                db.SaveChanges();


            }
            catch (Exception ex)
            {
                return Content("Error de sistema: " + ex.Message);
            }
            return Content("1");
        }

        #region Grid
        public ActionResult Listado()
        {

            return View();
        }

        public ActionResult JsonGrid([DataSourceRequest] DataSourceRequest request)
        {
            IEnumerable<TableCadenasViewModel> lst = null;

            lst = from d in db.cadena.ToList()
                  where d.idEstado == 1
                  select new TableCadenasViewModel
                  {
                      id = d.id,
                      nombre = d.nombre,
                      prefijo = d.cadenaSugerida,
                      tipoGiro = d.cGiroComercial.nombre ?? ""
                  };


            return Json(lst.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region HELPERS
        public void ObtenerComponentes()
        {

            ViewBag.lstGiros = Models.HelperModels.Giro.getGirosSL();
        }
        #endregion

        #region HELPERS
        public bool Validaciones(CadenaViewModel model)
        {
            if (Models.HelperModels.Cadena.Existe(model.nombre))
            {
                error = "El nombre de la cadena ya existe, intente con otro";
                return false;
            }
            if (model.cadena != null)
            {
                if (Models.HelperModels.Cadena.ExistePrefijo(model.cadena))
            {
                error = "El prefijo de la cadena ya existe, intente con otro";
                return false;
            }
            }
            return true;
        }
        public bool ValidacionesEditar(CadenaViewModel model)
        {
            if (Models.HelperModels.Cadena.Existe(model.nombre, model.id))
            {
                error = "El nombre de la cadena ya existe, intente con otro";
                return false;
            }
            if (model.cadena != null) {
                if (Models.HelperModels.Cadena.ExistePrefijo(model.cadena, model.id))
                {
                    error = "El prefijo de la cadena ya existe, intente con otro";
                    return false;
                }
            }
            

            return true;
        }
        #endregion
    }
}

Views/Cadena/Editar.cshtml
@model IntegramsaUltimate.Models.ViewModels.CadenaViewModel
@{
    Layout = null;
}

<form id="frmFormulario">
    <div class="bloque">
        @Html.HiddenFor(d => d.id)
        <div>
            @Html.LabelFor(d => d.nombre)
            @Html.TextBoxFor(d => d.nombre)
        </div>
        <div>
            <br />
            @Html.LabelFor(d => d.idGiro)
            @Html.DropDownListFor(d => d.idGiro, (SelectList)ViewBag.lstGiros)
        </div>
        <div>
            <br />
            @Html.LabelFor(d => d.cadena)
            @Html.TextBoxFor(d => d.cadena)
        </div>
        <div style="text-align:right;">
            <input class="btn-success" type="submit" value="Guardar" />
        </div>

    </div>

</form>

<script>

    $(document).ready(function () {

        //actualizar el formulario
        $("#frmFormulario").submit(function (e) {

            e.preventDefault();

            jsShowWindowLoad();

            url="@Url.Content("~/Cadena/GuardarEditar")"
            parametros = $(this).serialize();

            $.ajax({
                type: "POST",
                url: url,
                data: parametros,

                success: function (data) {

                    if (data == "1") {
                        MensajeExito("Cadena modificada con éxito");
                        jsCloseDialog();

                        jsRefrescaGrid("tabla")
                    } else {
                        MensajeError(data);
                    }
                    jsRemoveWindowLoad();
                },
                error: function (r) {
                    jsRemoveWindowLoad();
                    MensajeError("Error del servidor");
                }
            });

        })

    })
</script>

Views/Cadena/Index.cshtml
@{
    ViewBag.Title = "Cadenas";
}


<div style="background-color:#eee;padding:10px" class="head-module">
    <span style="margin-right:35px" class="modulo-titulo">Cadenas</span>

    <span class="boton-style" style="float:right" onclick="jsNuevo()">
        <img class="boton-image" src="~/Images/icon_new_element.png" />
    </span>
</div>
<hr />
<div id="divGrid"> 
    @Html.Partial("~/Views/Cadena/Listado.cshtml")
</div>

<script>

    $(document).ready(function () {
       
        
    })

    //funciones

    function jsNuevo() {

        url="@Url.Content("~/Cadena/Nuevo")";
        jsShowDialog(url, 400,300, "Nueva Cadena")
    }

    function jsEditar(id) {

        url="@Url.Content("~/Cadena/Editar")"+"?id="+id;
        jsShowDialog(url, 400,300, "Editar Cadena")
    }

    function jsEliminar(id){
        if(confirm("¿Estas seguro de eliminar la cadena?")){

            url = "@Url.Content("~/Cadena/Eliminar")";
            parametros = "id=" + id;
            jsShowWindowLoad();

            $.post(url, parametros, function (data) {

                if (data == "1") {
                    MensajeExito("Eliminado.")
                    jsRefrescaGrid("tabla")
                } else {
                    MensajeError(data) //trae el error data
                } 

                jsRemoveWindowLoad();
            })


        }
    }
</script>

Views/Cadena/Listado.cshtml
@{
    Layout = null;
}

 @(Html.Kendo().Grid<IntegramsaUltimate.Models.TableViewModels.TableCadenasViewModel>()
                    .Name("tabla")

                     .Columns(c =>
                        {
                            c.Bound(p => p.id).Title("#").Hidden("true");
                            c.Bound(p => p.nombre).Title("Nombre");
                            c.Bound(p => p.tipoGiro).Title("Giro");
                             c.Bound(p => p.prefijo).Title("Prefijo de Determinante");
                            c.Bound(p => p.id).ClientTemplate(@"
                                                                <img class='imgGrid' src='/Images/icon_edit.png' onclick='jsEditar(#=id#)' /> |
                                                                <img class='imgGrid' src='/Images/icon_delete.png' onclick='jsEliminar(#=id#)' />")
                                                             .Title("").Width(150);

                        })
                        .ToolBar(tools => tools.Excel())
                        .Pageable()
                        .Sortable()
                        .Filterable()
                       
                        .Excel(excel => excel
                            .FileName("reporte.xlsx")
                            .AllPages(true)
                             .ProxyURL(Url.Action("JsonGrid", "Cadena"))
                         )
                        .Resizable(resize => resize.Columns(true))
                        .DataSource(d => d.Ajax()
                            .Sort(sort=>sort.Add("id").Descending())
                           .Read(r => r.Action("JsonGrid", "Cadena"))
                        )

        )

Views/Cadena/Nuevo.cshtml
@model IntegramsaUltimate.Models.ViewModels.CadenaViewModel
@{
    Layout = null;
}

<form id="frmFormulario" >  
    <div class="bloque">
        <div>
            @Html.LabelFor(d => d.nombre)
            @Html.TextBoxFor(d => d.nombre)
        </div>
        <div>
            <br />
            @Html.LabelFor(d => d.idGiro)
            @Html.DropDownListFor(d => d.idGiro, (SelectList)ViewBag.lstGiros)
        </div>
        <div>
            <br />
            @Html.LabelFor(d => d.cadena)
            @Html.TextBoxFor(d => d.cadena)
        </div>
        <br />
        <div style="text-align:right;">
            <input class="btn-success" type="submit" value="Guardar" />
        </div>

    </div>
   
</form>

<script>

    $(document).ready(function () {

        //actualizar el formulario
        $("#frmFormulario").submit(function (e) {

            e.preventDefault();

            jsShowWindowLoad();

            url="@Url.Content("~/Cadena/Guardar")"
            parametros = $(this).serialize();
           
            $.ajax({
                type: "POST",
                url: url,
                data: parametros,
  
                success: function (data) {

                    if (data == "1") {
                        MensajeExito("Cadena agregada con éxito");
                        jsCloseDialog();

                        jsRefrescaGrid("tabla")
                    } else {
                        MensajeError(data);
                    }
                    jsRemoveWindowLoad();
                },
                error: function (r) {
                    jsRemoveWindowLoad();
                    MensajeError("Error del servidor");
                }
            });

        })

    })
</script>