Models/HelperModels/Formato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntegramsaUltimate.Models.HelperModels
{
    public class Formato
    {
        public static SelectList getFormatosSL()
        {
            try
            {
                IntegramsaUltimateEntities db = new IntegramsaUltimateEntities();
                var lst = from d in db.formatoTienda
                          where d.idEstado==1
                          select d;

                SelectList slc = new SelectList(lst, "id", "nombre");

                return slc;
            }
            catch { return null; }
        }
    }
}

Models/ViewModels/FormatoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IntegramsaUltimate.Models.ViewModels
{
    public class FormatoViewModel
    {
        public int id { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "El campo nombre no admite mas de 50 caracteres")]
        [Display(Name = "*Nombre")]
        public string nombre { get; set; }

        [Required]
        [Display(Name = "*Cadena")]
        public int? idCadena { get; set; }
    }
}

Controllers/FormatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IntegramsaUltimate.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using IntegramsaUltimate.Models.TableViewModels;
using IntegramsaUltimate.Models.ViewModels;
using System.Data.Entity;

namespace IntegramsaUltimate.Controllers
{
    public class FormatoController : BaseController
    {
        // GET: Formato
        public ActionResult Index()
        {
            ViewBag.lstCadenas = Models.HelperModels.Cadena.getCadenasSL();

            return View();
        }

        public ActionResult Nuevo(int idCadena)
        {
            ObtieneSesion();

            FormatoViewModel model = new FormatoViewModel();
            model.idCadena = idCadena;

            return View(model);
        }

        [HttpPost]
        public ActionResult Guardar(FormatoViewModel model)
        {
            try
            {
                //model es valido
                if (!ModelState.IsValid)
                {
                    return Content(getErroresModelo());
                }

               
                //guardamos
                formatoTienda oFormato = new formatoTienda();
                oFormato.idEstado = 1;
                oFormato.fecha = DateTime.Now;
                oFormato.nombre = model.nombre;
                oFormato.idCadena = model.idCadena;

                db.formatoTienda.Add(oFormato);
                db.SaveChanges();

                return Content("1");

            }
            catch (Exception ex)
            {
                return Content("Ocurrio un error: " + ex.Message);
            }
        }



        public ActionResult Editar(int id)
        {

            //obtenemos el usuario
            formatoTienda oFormato = db.formatoTienda.Find(id);

            FormatoViewModel model = new FormatoViewModel();
            model.nombre = oFormato.nombre;
            model.idCadena = oFormato.idCadena;
            model.id = oFormato.id;


            return View(model);
        }

        [HttpPost]
        public ActionResult GuardarEditar(FormatoViewModel model)
        {
            try
            {
                //model es valido
                if (!ModelState.IsValid)
                {
                    return Content(getErroresModelo());
                }

                //guardamos
                formatoTienda oFormato = db.formatoTienda.Find(model.id);
                oFormato.idEstado = 1;
                oFormato.fecha = DateTime.Now;
                oFormato.nombre = model.nombre;
                oFormato.idCadena = model.idCadena;

                db.Entry(oFormato).State = EntityState.Modified;
                db.SaveChanges();

                return Content("1");

            }
            catch (Exception ex)
            {
                return Content("Ocurrio un error: " + ex.Message);
            }
        }

        public ActionResult Eliminar(int id)
        {
            try
            {
                formatoTienda oFormato = db.formatoTienda.Find(id);

                oFormato.idEstado = 3;
                db.Entry(oFormato).State = EntityState.Modified;

                db.SaveChanges();


            }
            catch (Exception ex)
            {
                return Content("Error de sistema: " + ex.Message);
            }
            return Content("1");
        }


        #region Grid
        public ActionResult Listado(int idCadena)
        {


            return View(idCadena);
        }

        public ActionResult JsonGrid([DataSourceRequest] DataSourceRequest request, int idCadena)
        {
            IEnumerable<TableFormatosViewModel> lst = null;

            lst = from d in db.formatoTienda.ToList()
                  where d.idEstado == 1 && d.idCadena==idCadena
                  select new TableFormatosViewModel
                  {
                      id = d.id,
                      nombre = d.nombre
                  };


            return Json(lst.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

Views/Formato/Editar.cshtml
@model IntegramsaUltimate.Models.ViewModels.FormatoViewModel
@{
    Layout = null;
}

<form id="frmFormulario">
    @Html.HiddenFor(d => d.idCadena)
    @Html.HiddenFor(d=>d.id)

    <div class="bloque">
        <div>
            @Html.LabelFor(d => d.nombre)
            @Html.TextBoxFor(d => d.nombre)
        </div>

        <div style="text-align:right;">
            <input class="btn-success" type="submit" value="Guardar" />
        </div>

    </div>

</form>

<script>

    $(document).ready(function () {

        //actualizar el formulario
        $("#frmFormulario").submit(function (e) {

            e.preventDefault();

            jsShowWindowLoad();

            url="@Url.Content("~/Formato/GuardarEditar")"
            parametros = $(this).serialize();

            $.ajax({
                type: "POST",
                url: url,
                data: parametros,

                success: function (data) {

                    if (data == "1") {
                        MensajeExito("Formato editado con éxito");
                        jsCloseDialog();

                        jsRefrescaGrid("tabla")
                    } else {
                        MensajeError(data);
                    }
                    jsRemoveWindowLoad();
                },
                error: function (r) {
                    jsRemoveWindowLoad();
                    MensajeError("Error del servidor");
                }
            });

        })

    })
</script>

Views/Formato/Index.cshtml
@{
    ViewBag.Title = "Formatos de tienda";
}


<div style="background-color:#eee;padding:10px" class="head-module">
    <span style="margin-right:35px" class="modulo-titulo">@ViewBag.Title</span>

   

    <span class="boton-style" style="float:right" onclick="jsNuevo()">
        <img class="boton-image" src="~/Images/icon_new_element.png" />
    </span>
    <span>
        <label>Cadenas</label>
        @Html.DropDownList("cboCadenas", (SelectList)ViewBag.lstCadenas,null, new { style="width:200px;"})
    </span>
</div>
<hr />
<div id="divGrid">
    
</div>

<script>

    $(document).ready(function () {
        $("#cboCadenas").change(function () {

            idCadena = $(this).prop("value");
            
            url = "@Url.Content("~/Formato/Listado")"+"?idCadena="+idCadena
            
            $("#divGrid").load(url);

        })

        $("#cboCadenas").change(); //invocamos el listado

    })

    //funciones

    function jsNuevo() {

        idCadena = $("#cboCadenas").prop("value");

        url="@Url.Content("~/Formato/Nuevo")"+"?idCadena="+idCadena;
        jsShowDialog(url, 400,150, "Nuevo Formato")
    }

    function jsEditar(id) {

        url="@Url.Content("~/Formato/Editar")"+"?id="+id;
        jsShowDialog(url, 400,150, "Editar Formato")
    }

    function jsEliminar(id){
        if(confirm("¿Estas seguro de eliminar el formato?")){

            url = "@Url.Content("~/Formato/Eliminar")";
            parametros = "id=" + id;
            jsShowWindowLoad();

            $.post(url, parametros, function (data) {

                if (data == "1") {
                    MensajeExito("Eliminado.")
                    jsRefrescaGrid("tabla")
                } else {
                    MensajeError(data) //trae el error data
                }

                jsRemoveWindowLoad();
            })


        }
    }
</script>

Views/Formato/Listado.cshtml
@model int
@{
    Layout = null;
    int idCadena = Model;
}

<div class="row">

    <div class="col-md-12">
        @(Html.Kendo().Grid<IntegramsaUltimate.Models.TableViewModels.TableFormatosViewModel>()
                    .Name("tabla")

                     .Columns(c =>
                        {
                            c.Bound(p => p.id).Title("#").Width(50);
                            c.Bound(p => p.nombre).Title("Nombre");
                            c.Bound(p => p.id).ClientTemplate(@"
                                                                <img class='imgGrid' src='/Images/icon_edit.png' onclick='jsEditar(#=id#)' /> |
                                                                <img class='imgGrid' src='/Images/icon_delete.png' onclick='jsEliminar(#=id#)' />")
                                                             .Title("").Width(150);

                        })
                        .ToolBar(tools => tools.Excel())
                        .Pageable()
                        .Sortable()
                        .Filterable()

                        .Excel(excel => excel
                            .FileName("reporte.xlsx")
                            .AllPages(true)
                             .ProxyURL(Url.Action("JsonGrid", "Formato", new { idCadena = idCadena }))
                         )
                        .Resizable(resize => resize.Columns(true))
                        .DataSource(d => d.Ajax()
                            .Sort(sort => sort.Add("id").Descending())
                           .Read(r => r.Action("JsonGrid", "Formato", new { idCadena = idCadena }))
                        )

        )
    </div>
</div>

Views/Formato/Nuevo.cshtml
@model IntegramsaUltimate.Models.ViewModels.FormatoViewModel
@{
    Layout = null;
}

<form id="frmFormulario">
    @Html.HiddenFor(d=>d.idCadena)
    <div class="bloque">
        <div>
            @Html.LabelFor(d => d.nombre)
            @Html.TextBoxFor(d => d.nombre)
      
        </div>
        
        <div style="text-align:right;">
            <input class="btn-success" type="submit" value="Guardar" />
        </div>

    </div>

</form>

<script>

    $(document).ready(function () {

        //actualizar el formulario
        $("#frmFormulario").submit(function (e) {

            e.preventDefault();

            jsShowWindowLoad();

            url="@Url.Content("~/Formato/Guardar")"
            parametros = $(this).serialize();

            $.ajax({
                type: "POST",
                url: url,
                data: parametros,

                success: function (data) {

                    if (data == "1") {
                        MensajeExito("Formato agregado con éxito");
                        jsCloseDialog();

                        jsRefrescaGrid("tabla")
                    } else {
                        MensajeError(data);
                    }
                    jsRemoveWindowLoad();
                },
                error: function (r) {
                    jsRemoveWindowLoad();
                    MensajeError("Error del servidor");
                }
            });

        })

    })
</script>